// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ecRpuAnYy4nftFeWhJKmXt
// Component: KnmhLqOi2Vfx
import * as React from "react";
import {
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  useCurrentUser,
  useDollarState
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import PageLayout from "../../PageLayout"; // plasmic-import: IzMlfHGyHpm3/component
import { AntdDatePicker } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import { datePickerHelpers as AntdDatePicker_Helpers } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import Statistic from "../../Statistic"; // plasmic-import: nH1BxDDFpqfi/component
import { AntdSelect } from "@plasmicpkgs/antd5/skinny/registerSelect";
import { SimpleChart } from "@plasmicpkgs/react-chartjs-2";
import { useScreenVariants as useScreenVariants_6WjHx4LTkSfu } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6wjHx4LTkSFU/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ecRpuAnYy4nftFeWhJKmXt/projectcss
import sty from "./PlasmicBusinessMetrics.module.css"; // plasmic-import: KnmhLqOi2Vfx/css
import image7Hg2LBiX9Rb99 from "./images/image7.svg"; // plasmic-import: Hg2LBiX9rb99/picture
import orderIcon0RXuqFu6ZsSz from "./images/orderIcon.svg"; // plasmic-import: 0rXuqFU6zsSz/picture
import dollarIconBnQcP1KoYLw from "./images/dollarIcon.svg"; // plasmic-import: BNQcP1KoY_Lw/picture

createPlasmicElementProxy;

export const PlasmicBusinessMetrics__VariantProps = new Array();

export const PlasmicBusinessMetrics__ArgProps = new Array();

const $$ = {};

function PlasmicBusinessMetrics__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "start.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      },
      {
        path: "end.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ``,
        onMutate: generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      },
      {
        path: "select.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => "month"
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    topRevByCountryInDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "3gDMibUwZhkSjkUSK6gfBF",
        opId: "602ab03d-2078-433f-9395-2e953e6898f4",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.602ab03d-2078-433f-9395-2e953e6898f4.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    ordersByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "3gDMibUwZhkSjkUSK6gfBF",
        opId: "a34740a4-58d8-4ff4-8a20-5c14102fdb2d",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.a34740a4-58d8-4ff4-8a20-5c14102fdb2d.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    signupsByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "3gDMibUwZhkSjkUSK6gfBF",
        opId: "92bb3371-7e0b-47b2-ba49-8a18ed088ca9",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.92bb3371-7e0b-47b2-ba49-8a18ed088ca9.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    totalRevByCustomDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "3gDMibUwZhkSjkUSK6gfBF",
        opId: "af9c1fcf-2753-47c7-a4fa-12befa45df19",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.af9c1fcf-2753-47c7-a4fa-12befa45df19.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    monthlyRevByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "3gDMibUwZhkSjkUSK6gfBF",
        opId: "dda223c1-cc86-4e7a-9228-f62ea95da2a9",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.dda223c1-cc86-4e7a-9228-f62ea95da2a9.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    quarterlyRevByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "3gDMibUwZhkSjkUSK6gfBF",
        opId: "5f065747-c5cf-4996-a6b1-687a5a384de4",
        userArgs: {
          query: [$state.start.value, $state.end.value]
        },
        cacheKey: `plasmic.$.5f065747-c5cf-4996-a6b1-687a5a384de4.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6WjHx4LTkSfu()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  <section
                    className={classNames(projectcss.all, sty.section__hOgdV)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__sAdla)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Business Metrics"}
                      </h1>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__xmYl0)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__treTm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pqYE
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2___34M84
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Custom date range analysis"}
                            </span>
                          </React.Fragment>
                        </h2>
                      </div>
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__itMZo
                        )}
                      >
                        {(() => {
                          const child$Props = {
                            allowClear: true,
                            bordered: true,
                            className: classNames("__wab_instance", sty.start),
                            onChange:
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["start", "value"],
                                AntdDatePicker_Helpers
                              ),
                            picker: "date",
                            popupBodyClassName: classNames({
                              [sty["pcls_zoE40GfjAMv3"]]: true
                            }),
                            popupClassName: classNames({
                              [sty["pcls_Los09rfIEkCM"]]: true
                            }),
                            popupHeaderClassName: classNames({
                              [sty["pcls_NQ85cEDw6MOH"]]: true
                            }),
                            popupScopeClassName: sty["start__datePickerPopup"],
                            showTime: false,
                            value: generateStateValueProp($state, [
                              "start",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "start.value"
                              }
                            ],

                            [],
                            AntdDatePicker_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdDatePicker
                              data-plasmic-name={"start"}
                              data-plasmic-override={overrides.start}
                              {...child$Props}
                            />
                          );
                        })()}
                        {(() => {
                          const child$Props = {
                            allowClear: true,
                            bordered: true,
                            className: classNames("__wab_instance", sty.end),
                            defaultValue: ``,
                            onChange:
                              generateStateOnChangePropForCodeComponents(
                                $state,
                                "value",
                                ["end", "value"],
                                AntdDatePicker_Helpers
                              ),
                            picker: "date",
                            popupScopeClassName: sty["end__datePickerPopup"],
                            value: generateStateValueProp($state, [
                              "end",
                              "value"
                            ])
                          };
                          initializeCodeComponentStates(
                            $state,
                            [
                              {
                                name: "value",
                                plasmicStateName: "end.value"
                              }
                            ],

                            [],
                            AntdDatePicker_Helpers ?? {},
                            child$Props
                          );
                          return (
                            <AntdDatePicker
                              data-plasmic-name={"end"}
                              data-plasmic-override={overrides.end}
                              {...child$Props}
                            />
                          );
                        })()}
                      </Stack__>
                    </div>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___1R5I)}
                    >
                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__kLcBp
                        )}
                        hideTrendTracker={true}
                        number={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__dZ5Lc
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $queries.signupsByDateRange.data[0]
                                    .signup_count;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </h2>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__ae9Wa
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__hyASz
                              )}
                              style={(() => {
                                try {
                                  return undefined;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return undefined;
                                  }
                                  throw e;
                                }
                              })()}
                            >
                              {"Sign-ups"}
                            </div>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__jhoOh)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: image7Hg2LBiX9Rb99,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__f06TB
                        )}
                        hideTrendTracker={true}
                        number={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__wmY2U
                            )}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return $queries.ordersByDateRange.data[0]
                                    .order_count;
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </h2>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__pwd2
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__idZdG
                              )}
                            >
                              {"Orders"}
                            </div>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__vVi2L)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: orderIcon0RXuqFu6ZsSz,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__h5X2N
                        )}
                        hideTrendTracker={true}
                        number={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___4TAi
                            )}
                          >
                            <h2
                              className={classNames(
                                projectcss.all,
                                projectcss.h2,
                                projectcss.__wab_text,
                                sty.h2__htoO8
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return (
                                      "$" +
                                      Intl.NumberFormat("en").format(
                                        $queries.totalRevByCustomDateRange
                                          .data[0].total_revenue
                                      )
                                    );
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "NULL";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </h2>
                          </div>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__mdOhy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fHqrZ
                              )}
                            >
                              {"Revenue"}
                            </div>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__hhLu)}
                              displayHeight={"auto"}
                              displayMaxHeight={"24px"}
                              displayMaxWidth={"24px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: dollarIconBnQcP1KoYLw,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />
                    </Stack__>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__tHy4S)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__j26Vz)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__nde67
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__baDIr
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Revenue Trends"}
                            </span>
                          </React.Fragment>
                        </h2>
                        <AntdSelect
                          data-plasmic-name={"select"}
                          data-plasmic-override={overrides.select}
                          bordered={true}
                          className={classNames("__wab_instance", sty.select)}
                          defaultOpen={false}
                          defaultStylesClassName={classNames(
                            projectcss.root_reset,
                            projectcss.plasmic_default_styles,
                            projectcss.plasmic_mixins,
                            projectcss.plasmic_tokens,
                            plasmic_antd_5_hostless_css.plasmic_tokens,
                            plasmic_plasmic_rich_components_css.plasmic_tokens
                          )}
                          defaultValue={"month"}
                          onChange={generateStateOnChangeProp($state, [
                            "select",
                            "value"
                          ])}
                          options={(() => {
                            const __composite = [
                              { value: null, label: null, type: null },
                              { value: null, label: null, type: "option" }
                            ];

                            __composite["0"]["value"] = "month";
                            __composite["0"]["label"] = "month";
                            __composite["0"]["type"] = "option";
                            __composite["1"]["value"] = "quarterly";
                            __composite["1"]["label"] = "quarterly";
                            return __composite;
                          })()}
                          placeholder={"Select..."}
                          popupScopeClassName={sty["select__popup"]}
                          value={generateStateValueProp($state, [
                            "select",
                            "value"
                          ])}
                        />
                      </div>
                      <SimpleChart
                        className={classNames(
                          "__wab_instance",
                          sty.chart__yUc6H
                        )}
                        data={
                          $state.select.value === "month"
                            ? $queries.monthlyRevByDateRange.data
                            : $queries.quarterlyRevByDateRange.data
                        }
                        interactive={false}
                        title={``}
                        type={"bar"}
                      />
                    </Stack__>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__aaTjd)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox___6XEc)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__lJrde
                        )}
                      >
                        <h2
                          className={classNames(
                            projectcss.all,
                            projectcss.h2,
                            projectcss.__wab_text,
                            sty.h2__cnfcn
                          )}
                        >
                          <React.Fragment>
                            <span
                              className={
                                "plasmic_default__all plasmic_default__span"
                              }
                              style={{ fontWeight: 500 }}
                            >
                              {"Revenue per country: within the last year"}
                            </span>
                          </React.Fragment>
                        </h2>
                      </div>
                      <SimpleChart
                        className={classNames(
                          "__wab_instance",
                          sty.chart__pg4Cc
                        )}
                        data={$queries.topRevByCountryInDateRange.data}
                        interactive={false}
                        labelField={"country"}
                        title={"Revenue by country"}
                        type={"bar"}
                      />
                    </Stack__>
                  </section>
                </React.Fragment>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "h1", "start", "end", "select"],
  pageLayout: ["pageLayout", "h1", "start", "end", "select"],
  h1: ["h1"],
  start: ["start"],
  end: ["end"],
  select: ["select"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicBusinessMetrics__ArgProps,
          internalVariantPropNames: PlasmicBusinessMetrics__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicBusinessMetrics__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicBusinessMetrics";
  } else {
    func.displayName = `PlasmicBusinessMetrics.${nodeName}`;
  }
  return func;
}

function withUsePlasmicAuth(WrappedComponent) {
  const WithUsePlasmicAuthComponent = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "ecRpuAnYy4nftFeWhJKmXt"
    });
    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicBusinessMetrics = Object.assign(
  // Top-level PlasmicBusinessMetrics renders the root element
  withUsePlasmicAuth(makeNodeComponent("root")),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    h1: makeNodeComponent("h1"),
    start: makeNodeComponent("start"),
    end: makeNodeComponent("end"),
    select: makeNodeComponent("select"),
    // Metadata about props expected for PlasmicBusinessMetrics
    internalVariantProps: PlasmicBusinessMetrics__VariantProps,
    internalArgProps: PlasmicBusinessMetrics__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicBusinessMetrics;
/* prettier-ignore-end */
